import type { TerminalDashboardData } from '../../lib/gimml-terminal-dashboard/types';

export function TerminalReport({ transactions }: { transactions: TerminalDashboardData['transactions'] }) {
  const approved = transactions.filter(transaction => transaction.status === 'approved');
  const total = approved.reduce((sum, transaction) => sum + Number(transaction.amount_minor), 0);
  return <section className="rounded-xl border bg-white p-6 shadow-sm"><h2 className="text-xl font-semibold">Unified terminal reporting</h2><div className="mt-4 grid gap-3 sm:grid-cols-3"><div className="rounded bg-gray-50 p-4"><div className="text-sm text-gray-500">Recent transactions</div><div className="text-2xl font-bold">{transactions.length}</div></div><div className="rounded bg-gray-50 p-4"><div className="text-sm text-gray-500">Approved</div><div className="text-2xl font-bold">{approved.length}</div></div><div className="rounded bg-gray-50 p-4"><div className="text-sm text-gray-500">Approved volume</div><div className="text-2xl font-bold">${(total / 100).toFixed(2)}</div></div></div>
    <div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b"><th className="p-2">Date</th><th className="p-2">Serial</th><th className="p-2">Type</th><th className="p-2">Amount</th><th className="p-2">Status</th><th className="p-2">Card</th><th className="p-2">Auth / batch</th><th className="p-2">Program</th></tr></thead><tbody>{transactions.map(transaction => <tr className="border-b" key={transaction.transaction_id}><td className="p-2">{new Date(transaction.occurred_at).toLocaleString()}</td><td className="p-2 font-mono">{transaction.serial_number}</td><td className="p-2">{transaction.transaction_type ?? 'sale'}<div className="text-xs text-gray-500">{transaction.entry_method ?? ''}</div></td><td className="p-2">{transaction.currency} {(Number(transaction.amount_minor) / 100).toFixed(2)}</td><td className="p-2">{transaction.status}</td><td className="p-2">{transaction.card_type ?? 'Card'} {transaction.last4 ? `•••• ${transaction.last4}` : ''}</td><td className="p-2">{transaction.authorization_code ?? '—'}<div className="text-xs text-gray-500">{transaction.batch_id ? `Batch ${transaction.batch_id}` : ''}</div></td><td className="p-2">{transaction.closed_loop_program ?? 'Open loop'}</td></tr>)}</tbody></table>{transactions.length === 0 && <div className="p-5 text-center text-sm text-gray-500">No unified terminal transactions have been received yet.</div>}</div>
  </section>;
}
