'use client';

import Link from 'next/link';
import type { MerchantRecord, SalesRepresentative } from '../lib/merchant-management';

export default function MerchantList({ merchants, representatives, owner, onStatusChange, onDelete }: { merchants: MerchantRecord[]; representatives: SalesRepresentative[]; owner: boolean; onStatusChange: (merchant: MerchantRecord, action: 'deactivate' | 'reactivate' | 'archive') => void; onDelete: (merchant: MerchantRecord) => void }) {
  const repNames = new Map(representatives.map(rep => [rep.id, rep.name || rep.email || 'Unnamed representative']));
  return <div className="mt-5 grid gap-3">{merchants.map(merchant => <article key={merchant.id} className="rounded-xl border bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><Link href={`/admin/merchant/${merchant.slug}`} className="min-w-0 flex-1"><div className="flex items-center gap-2"><span className="font-semibold">{merchant.name}</span><span className={`rounded-full px-2 py-0.5 text-xs ${merchant.status === 'archived' ? 'bg-gray-200 text-gray-700' : merchant.status === 'inactive' ? 'bg-amber-100 text-amber-800' : 'bg-green-100 text-green-800'}`}>{merchant.status}</span>{merchant.is_test && <span className="rounded-full bg-amber-100 px-2 py-0.5 text-xs text-amber-800">test</span>}</div><div className="mt-1 text-sm text-gray-600">{merchant.primary_contact_name || 'No primary contact'}{merchant.primary_contact_email ? ` · ${merchant.primary_contact_email}` : ''}</div><div className="mt-1 text-xs text-gray-500">{repNames.get(merchant.sales_rep_id || '') || 'Unassigned'} · {merchant.currency} · {merchant.timezone} · {merchant.active_device_count}/{merchant.device_count} devices active</div></Link>{owner && merchant.status !== 'archived' && <div className="flex flex-wrap justify-end gap-2">{merchant.status === 'active' ? <button type="button" onClick={() => onStatusChange(merchant, 'deactivate')} className="rounded border border-amber-400 px-3 py-2 text-sm text-amber-800">Deactivate</button> : <button type="button" onClick={() => onStatusChange(merchant, 'reactivate')} className="rounded border border-green-400 px-3 py-2 text-sm text-green-800">Reactivate merchant</button>}<button type="button" onClick={() => onStatusChange(merchant, 'archive')} className="rounded border px-3 py-2 text-sm">Archive</button>{merchant.is_test && <button type="button" onClick={() => onDelete(merchant)} className="rounded border border-red-300 px-3 py-2 text-sm text-red-700">Permanently delete empty merchant</button>}</div>}</div></article>)}{merchants.length === 0 && <div className="rounded-xl border border-dashed p-8 text-center text-gray-500">No merchants match this search.</div>}</div>;
}
