'use client';

import Link from 'next/link';
import type { MerchantRecord, SalesRepresentative } from '../lib/merchant-management';

export default function MerchantList({ merchants, representatives, owner, onArchive, onDelete }: { merchants: MerchantRecord[]; representatives: SalesRepresentative[]; owner: boolean; onArchive: (merchant: MerchantRecord) => void; onDelete: (merchant: MerchantRecord) => void }) {
  const repNames = new Map(representatives.map(rep => [rep.id, rep.name || rep.email || 'Unnamed representative']));
  return <div className="mt-5 grid gap-3">{merchants.map(merchant => <article key={merchant.id} className="rounded-xl border bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><Link href={`/admin/merchant/${merchant.slug}`} className="min-w-0 flex-1"><div className="flex items-center gap-2"><span className="font-semibold">{merchant.name}</span><span className={`rounded-full px-2 py-0.5 text-xs ${merchant.status === 'archived' ? 'bg-gray-200 text-gray-700' : 'bg-green-100 text-green-800'}`}>{merchant.status}</span></div><div className="mt-1 text-sm text-gray-600">{merchant.primary_contact_name || 'No primary contact'}{merchant.primary_contact_email ? ` · ${merchant.primary_contact_email}` : ''}</div><div className="mt-1 text-xs text-gray-500">{repNames.get(merchant.sales_rep_id || '') || 'Unassigned'} · {merchant.currency} · {merchant.timezone}</div></Link>{owner && <div className="flex gap-2"><button type="button" disabled={merchant.status === 'archived'} onClick={() => onArchive(merchant)} className="rounded border px-3 py-2 text-sm disabled:opacity-40">Archive</button><button type="button" onClick={() => onDelete(merchant)} className="rounded border border-red-300 px-3 py-2 text-sm text-red-700">Delete test merchant</button></div>}</div></article>)}{merchants.length === 0 && <div className="rounded-xl border border-dashed p-8 text-center text-gray-500">No merchants match this search.</div>}</div>;
}
