const CAPABILITIES=new Set(['CARD_PRESENT','KEYED_ENTRY','FIXED_AMOUNT','KEYPAD_AMOUNT','PRESETS','INCREMENT','LOCAL_MERCHANT_MENU','VOID','REFUND','SETTLEMENT','CLOSED_LOOP_IDENTIFY','DASHBOARD_REPORTING','ADVANCED_REPORTING','FLEET_HEALTH','FLEET_LOCATION']);
const PROFILES=new Set(['GIMML_ONE','GIMML_MINI','CUSTOM']);
const LAYOUTS=new Set(['ONE','MINI']);
const STATES=new Set(['trialing','active','grace','suspended','expired']);

function requireActor(actor,merchantId,permission){if(!actor||actor.merchantId!==merchantId||!actor.permissions?.includes(permission))throw new Error('Dashboard authorization denied');}
function id(value,name){if(typeof value!=='string'||!/^[0-9a-f-]{36}$/i.test(value))throw new Error(`Invalid ${name}`);return value;}
function capability(value){if(!CAPABILITIES.has(value))throw new Error('Invalid capability');return value;}

export class DashboardAdminService{
 constructor(repository,{pairingPepper}={}){this.repository=repository;this.pairingPepper=pairingPepper;}
 async overview(actor,merchantId){requireActor(actor,merchantId,'terminal:read');return this.repository.merchantOverview(merchantId);}
 async catalog(actor,merchantId){requireActor(actor,merchantId,'billing:read');return this.repository.catalogAndPlans();}
 async report(actor,merchantId,{from,to,deviceId=null}){requireActor(actor,merchantId,'reporting:read');const start=new Date(from),end=new Date(to);if(!Number.isFinite(start.getTime())||!Number.isFinite(end.getTime())||end<=start||end-start>366*86400000)throw new Error('Invalid report range');return this.repository.merchantReport(merchantId,start,end,deviceId? id(deviceId,'device'):null);}
 async setProfile(actor,merchantId,{deviceId,profile,layout}){requireActor(actor,merchantId,'terminal:write');id(deviceId,'device');if(!PROFILES.has(profile)||!LAYOUTS.has(layout)||profile==='GIMML_ONE'&&layout!=='ONE'||profile==='GIMML_MINI'&&layout!=='MINI')throw new Error('Invalid profile layout');return this.repository.setDeviceProfile(merchantId,deviceId,profile,layout,actor.id);}
 async setTerminalSettings(actor,merchantId,{deviceId,settings}){requireActor(actor,merchantId,'terminal:write');id(deviceId,'device');const s=validateSettings(settings);return this.repository.setDeviceSettings(merchantId,deviceId,s,actor.id);}
 async setEntitlement(actor,merchantId,{sku,capability:cap,state,quantity=1,expiresAt=null}){requireActor(actor,merchantId,'billing:write');capability(cap);if(!STATES.has(state)||!Number.isInteger(quantity)||quantity<0)throw new Error('Invalid entitlement');return this.repository.setMerchantEntitlement(merchantId,{sku,capability:cap,state,quantity,expiresAt},actor.id);}
 async assignCapability(actor,merchantId,{deviceId,entitlementId,assigned}){requireActor(actor,merchantId,'terminal:write');id(deviceId,'device');id(entitlementId,'entitlement');return this.repository.setDeviceAssignment(merchantId,deviceId,entitlementId,assigned===true,actor.id);}
 async setClosedLoopProgram(actor,merchantId,input){requireActor(actor,merchantId,'terminal:write');if(!/^[0-9]{6,8}$/.test(input.binPrefix??'')||typeof input.displayName!=='string'||!input.displayName.trim())throw new Error('Invalid closed-loop program');return this.repository.setClosedLoopProgram(merchantId,{...input,displayName:input.displayName.trim()},actor.id);}
 async queueCommand(actor,merchantId,input){requireActor(actor,merchantId,'command:write');id(input.deviceId,'device');const map={void:'VOID',refund:'REFUND',settlement:'SETTLEMENT'};if(!map[input.action])throw new Error('Invalid command');if(input.action==='refund'&&(!Number.isSafeInteger(input.amountMinor)||input.amountMinor<=0))throw new Error('Refund amount required');if(input.action==='void'&&!(input.processorTransactionId??'').trim())throw new Error('Processor transaction required');return this.repository.createAuthorizedCommand(merchantId,{...input,capability:map[input.action]},actor.id);}
 async createPairingCode(actor,merchantId,{deviceId,applicationId,signingCertificateSha256}){requireActor(actor,merchantId,'terminal:pair');id(deviceId,'device');if(!this.pairingPepper||this.pairingPepper.length<32)throw new Error('Pairing service is unavailable');if(!/^com\.gimml\.terminal(?:\.debug)?$/.test(applicationId??'')||!/^[a-f0-9]{64}$/.test(signingCertificateSha256??''))throw new Error('Invalid APK identity');const alphabet='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';let code='';for(const byte of randomBytes(12))code+=alphabet[byte%alphabet.length];const serial=await this.repository.deviceSerial(merchantId,deviceId);if(!serial)throw new Error('Device not found');const digest=createHmac('sha256',this.pairingPepper).update(`${serial}\n${code}`).digest();await this.repository.createDevicePairing(merchantId,{deviceId,codeDigest:digest,applicationId,signingCertificateSha256:Buffer.from(signingCertificateSha256,'hex'),expiresAt:new Date(Date.now()+10*60*1000)},actor.id);return {pairingCode:code,expiresInSeconds:600};}
}

function validateSettings(value){if(!value||!Number.isSafeInteger(value.default_cents)||!Array.isArray(value.preset_cents)||value.preset_cents.length!==3||!value.preset_cents.every(Number.isSafeInteger)||!Number.isSafeInteger(value.increment_cents)||!Number.isSafeInteger(value.maximum_cents)||value.maximum_cents<=0||!Number.isInteger(value.reset_seconds)||value.reset_seconds<5||value.reset_seconds>300)throw new Error('Invalid terminal settings');for(const amount of [value.default_cents,value.increment_cents,...value.preset_cents])if(amount<0||amount>value.maximum_cents)throw new Error('Invalid terminal amount');return {default_cents:value.default_cents,preset_cents:[...value.preset_cents],increment_cents:value.increment_cents,maximum_cents:value.maximum_cents,reset_seconds:value.reset_seconds};}

export const dashboardAdminInternals={validateSettings,requireActor};
import {createHmac,randomBytes} from 'node:crypto';
