import http from 'node:http';import {readFile} from 'node:fs/promises';import {extname} from 'node:path';import {fileURLToPath} from 'node:url';import pg from 'pg';import {PostgresTerminalRepository} from './postgres-repository.mjs';import {PostgresDashboardRepository} from './postgres-dashboard-repository.mjs';import {DashboardAdminService} from './dashboard-admin.mjs';import {createTerminalHttpHandler} from './http-handler.mjs';import {createDashboardHttpHandler} from './dashboard-http-handler.mjs';import {verifyDashboardSession} from './dashboard-session-auth.mjs';
import {classifyRoute} from './route-classifier.mjs';
import {resolveDashboardAsset} from './static-dashboard-path.mjs';
const required=name=>{const value=process.env[name];if(!value)throw new Error(`${name} is required`);return value;};
const pool=new pg.Pool({connectionString:required('DATABASE_URL'),ssl:process.env.PGSSL==='disable'?false:{rejectUnauthorized:true},max:Number(process.env.PG_POOL_MAX||10)});
const client={query:(...args)=>pool.query(...args),transaction:async work=>{const connection=await pool.connect();try{await connection.query('begin');const value=await work(connection);await connection.query('commit');return value;}catch(error){await connection.query('rollback');throw error;}finally{connection.release();}}};
const terminal=new PostgresTerminalRepository(client),dashboardRepo=new PostgresDashboardRepository(client);const pairingPepper=required('GIMML_PAIRING_PEPPER');const dashboardService=new DashboardAdminService(dashboardRepo,{pairingPepper});const sessionOptions={publicKeyDerBase64:required('GIMML_DASHBOARD_SESSION_PUBLIC_KEY_DER_BASE64'),issuer:required('GIMML_DASHBOARD_SESSION_ISSUER'),audience:required('GIMML_DASHBOARD_SESSION_AUDIENCE')};
const terminalHandler=createTerminalHttpHandler({repository:terminal,responsePrivateKeyDerBase64:required('GIMML_RESPONSE_PRIVATE_KEY_DER_BASE64'),pairingPepper});const dashboardHandler=createDashboardHttpHandler({service:dashboardService,authenticateActor:req=>verifyDashboardSession(req.headers.authorization,sessionOptions)});const dashboardRoot=fileURLToPath(new URL('../../dashboard/',import.meta.url));
async function body(request,limit=1024*1024){const chunks=[];let size=0;for await(const chunk of request){size+=chunk.length;if(size>limit)throw new Error('Request too large');chunks.push(chunk);}return Buffer.concat(chunks);}
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://localhost'),kind=classifyRoute(url.pathname);if(kind==='dashboard'){const match=url.pathname.match(/^\/api\/dashboard\/([^/]+)(\/.*)$/);if(!match)throw new Error('Invalid dashboard route');const result=await dashboardHandler({method:req.method,path:url.pathname,params:{merchantId:decodeURIComponent(match[1])},query:Object.fromEntries(url.searchParams),headers:req.headers,body:await body(req,256*1024)});return send(res,result);}if(kind==='terminal'){const result=await terminalHandler({method:req.method,path:url.pathname,headers:req.headers,body:await body(req)});return send(res,result);}const path=resolveDashboardAsset(dashboardRoot,url.pathname);if(!path)return send(res,{status:404,headers:{},body:Buffer.from('Not found')});const data=await readFile(path);return send(res,{status:200,headers:{'content-type':({'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8'}[extname(path)]||'application/octet-stream'),'cache-control':'no-store'},body:data});}catch(error){return send(res,{status:400,headers:{'content-type':'application/json'},body:Buffer.from(JSON.stringify({error:'Request rejected'}))});}});
function send(res,result){res.statusCode=result.status;for(const [key,value] of Object.entries(result.headers||{}))res.setHeader(key,value);res.setHeader('x-content-type-options','nosniff');res.setHeader('referrer-policy','no-referrer');res.setHeader('content-security-policy',"default-src 'self'; script-src 'self'; style-src 'self'; frame-ancestors 'none'; base-uri 'none'; form-action 'self'");res.end(result.body);}
const port=Number(process.env.PORT||8080);server.listen(port,'0.0.0.0',()=>console.log(`Gimml Terminal server listening on ${port}`));
for(const signal of ['SIGINT','SIGTERM'])process.on(signal,()=>server.close(()=>pool.end().finally(()=>process.exit(0))));
